steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sm-automation', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sm-automation']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sm-automation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sm-automation'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--set-env-vars'
      - 'MONGODB_URI=${_MONGODB_URI}'
      - '--set-env-vars'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - '--set-env-vars'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - '--set-env-vars'
      - 'GOOGLE_ID=${_GOOGLE_ID}'
      - '--set-env-vars'
      - 'GOOGLE_SECRET=${_GOOGLE_SECRET}'
      - '--set-env-vars'
      - 'CLAUDE_API_KEY=${_CLAUDE_API_KEY}'
      - '--set-env-vars'
      - 'FAL_AI_KEY=${_FAL_AI_KEY}'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_CONNECTIONS=${_NEXT_PUBLIC_CONNECTIONS}'

images:
  - 'gcr.io/$PROJECT_ID/sm-automation'
